### PR TITLE
Client side code for build_recipe page

### PR DESCRIPTION
**Pull request by alcaidet**
1. Added dynamic dropdowns for the "Food Category" and "Ingredient" selections using the ingredient information from the GET response from the server
2. Streamlined the build_recipe forms:
    a. Added the Recipe Name input field
    b. Made "amount" input fields more clear what they are asking for with placeholder text
    c. Relabeled "Enter Ingredient" button to "Add Ingredient to Recipe"
    d. Included 0.01 step attribute so "Amount" fields can hold decimals
3. Created payload object that holds: Recipe Name, Recipe Components as an array of objects, Recipe Description, and UserID
4. Added POST request that is bound to the "Finish Recipe" button that sends payload object to server
5. Included some code on POST route on server to show how to access all Recipe information  in the payload object

### CODE REVIEW

**Review by kedar-damle — CHANGES_REQUESTED** [review]
1. Please make recipe name input as Required
2. Please disable save feature for a guest user.
3. Please give an error message to the user if they are not logged in telling them save is disabled
4. Please disable save button until at least one ingredient is added.
5. Cannot delete ingredient once it is added.

**Comment by alcaidet** [comment]
Will also add Delete function for deleting ingredient from recipe

**Comment by alcaidet** [comment]
Addressed requests:
1. Please make recipe name input as Required
2. Please disable save feature for a guest user.
3. Please give an error message to the user if they are not logged in telling them save is disabled

Working on requests:
4. Please disable save button until at least one ingredient is added.
5. Cannot delete ingredient once it is added.

**Comment by alcaidet** [comment]
All requests have been addressed

**Review by kedar-damle — APPROVED** [review]

**Pull request merged**
